[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
invoice-detective = { path = "../invoice-detective" }
rocket = { version = "0.5.0" }
rocket_dyn_templates = { version = "0.1.0", features = ["tera"] }
thousands = "0.2.0"
